/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import clientapp.ChatRoom;
import clientapp.ChatRoomControl;
import clientapp.User;
import connection.Connection;
import java.io.IOException;
import java.net.UnknownHostException;

/**
 *
 * @author jose
 */
public class MainFrame extends javax.swing.JFrame {
    User currentUser;
    PrincipalPanel panelPrincipal;
    ChatRoomPanel chatRoom;
    Connection co;
    ChatRoomControl chc;
    Login lf;
    /**
     * Creates new form MainFrame
     */
    public MainFrame(User currentUser, Login lf) throws UnknownHostException, IOException {
        //initComponents();
        this.co = Connection.getInstanceConnection();
        this.currentUser = currentUser;
        this.lf = lf;
        panelPrincipal = new PrincipalPanel(currentUser, this, co);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.setContentPane(panelPrincipal);
        this.pack();
        //this.add(panelPrincipal);
    }
    
    public void joinChat(User u, String sala) throws IOException{
        String ChatRoomDesired = sala;
        String[] answer = co.requestChatRoom(u.getUser_name(), ChatRoomDesired).split("&");
        ChatRoom curretChatRoom = new ChatRoom(ChatRoomDesired);
        chc = new ChatRoomControl(curretChatRoom);
        chatRoom = new ChatRoomPanel(chc, u, this, co);
        curretChatRoom.addObserver(chatRoom);
        this.setContentPane(chatRoom);
        this.pack();
    }
    
    public void exitChat() throws UnknownHostException, IOException, InterruptedException{
        chc.stopCHC();
        panelPrincipal = new PrincipalPanel(currentUser, this, co);
        this.setContentPane(panelPrincipal);
        this.pack();
    }
    
    public MainFrame(){
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
